version: 2
jobs:
  build:
    docker:
      - image: gcc:8
    working_directory: ~/repo
    steps:
      - checkout
      - run: apt update -y && apt install -y git cmake lcov
      - run: ./test.sh
